//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foxminded.HryvniaRateBot.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotButtonsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotButtonsText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foxminded.HryvniaRateBot.App.Resources.BotButtonsText", typeof(BotButtonsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        public static string AprilText {
            get {
                return ResourceManager.GetString("AprilText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        public static string AugustText {
            get {
                return ResourceManager.GetString("AugustText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD (Canadian dollar).
        /// </summary>
        public static string CADText {
            get {
                return ResourceManager.GetString("CADText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Calendar.
        /// </summary>
        public static string CalendarButtonText {
            get {
                return ResourceManager.GetString("CalendarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHF (Swiss franc).
        /// </summary>
        public static string CHFText {
            get {
                return ResourceManager.GetString("CHFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string DecemberText {
            get {
                return ResourceManager.GetString("DecemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR (Euro).
        /// </summary>
        public static string EURText {
            get {
                return ResourceManager.GetString("EURText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string FebruaryText {
            get {
                return ResourceManager.GetString("FebruaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBP (British pound).
        /// </summary>
        public static string GBPText {
            get {
                return ResourceManager.GetString("GBPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string JanuaryText {
            get {
                return ResourceManager.GetString("JanuaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        public static string JulyText {
            get {
                return ResourceManager.GetString("JulyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string JuneText {
            get {
                return ResourceManager.GetString("JuneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string MarchText {
            get {
                return ResourceManager.GetString("MarchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string MayText {
            get {
                return ResourceManager.GetString("MayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string NovemberText {
            get {
                return ResourceManager.GetString("NovemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string OctoberText {
            get {
                return ResourceManager.GetString("OctoberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLN (Polish zloty).
        /// </summary>
        public static string PLNText {
            get {
                return ResourceManager.GetString("PLNText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEK (Swedish krona).
        /// </summary>
        public static string SEKText {
            get {
                return ResourceManager.GetString("SEKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        public static string SeptemberText {
            get {
                return ResourceManager.GetString("SeptemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📆 Today.
        /// </summary>
        public static string TodayButtonText {
            get {
                return ResourceManager.GetString("TodayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD (US Dollar).
        /// </summary>
        public static string USDollarText {
            get {
                return ResourceManager.GetString("USDollarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAU (Gold).
        /// </summary>
        public static string XAUText {
            get {
                return ResourceManager.GetString("XAUText", resourceCulture);
            }
        }
    }
}
