//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foxminded.HryvniaRateBot.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foxminded.HryvniaRateBot.App.Resources.BotMessage", typeof(BotMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Server request failed. There may be a heavy load, try again later. If the problem persists, please contact the support hotline 📞..
        /// </summary>
        public static string ApiRequestException {
            get {
                return ResourceManager.GetString("ApiRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privat Bank.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the 💸 currency, please:.
        /// </summary>
        public static string ChooseCurrency {
            get {
                return ResourceManager.GetString("ChooseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a 📅 date to view the currency rating {0} to UAH 🇺🇦.
        /// </summary>
        public static string EnterDate {
            get {
                return ResourceManager.GetString("EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 exchange rate {0} 
        ///Sale rate: {1} UAH
        ///Purchase rate: {2} UAH
        ///
        ///Date: {3}
        ///
        ///Information were taken from: {4}.
        /// </summary>
        public static string ExchangeRateInfo {
            get {
                return ResourceManager.GetString("ExchangeRateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option selected. Please try again..
        /// </summary>
        public static string InvalidOption {
            get {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Bank of Ukraine.
        /// </summary>
        public static string NBUText {
            get {
                return ResourceManager.GetString("NBUText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Looks like the bank doesn&apos;t have information for {0} on this date: {1}.
        /// </summary>
        public static string NoBankInfo {
            get {
                return ResourceManager.GetString("NoBankInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, something went wrong (nullable data 🅾️). Please, try again or contact support📞 if the problem persists..
        /// </summary>
        public static string NullMessageError {
            get {
                return ResourceManager.GetString("NullMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 You have chosen the date: {0}..
        /// </summary>
        public static string PickDate {
            get {
                return ResourceManager.GetString("PickDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You picked {0}.
        /// </summary>
        public static string PickedCurrencyText {
            get {
                return ResourceManager.GetString("PickedCurrencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📡 Starting a new operation with exchange rate..
        /// </summary>
        public static string StartNewOperation {
            get {
                return ResourceManager.GetString("StartNewOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❓ Unknown command..
        /// </summary>
        public static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏳ Please wait, your request is being processed!.
        /// </summary>
        public static string WaitMessageText {
            get {
                return ResourceManager.GetString("WaitMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome! I will help you with information about currency rate. You will see the available currencies and their price in 🇺🇦 UAH 🇺🇦 for any date from 2014 to today.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
